# RULE DEFINITION
VOLUME_THRESHOLD = 1000000  # measured in cm^3
DIMENSION_THRESHOLD = 150  # measured in cm
MASS_THRESHOLD = 20  # measured in kg

# STACK NAME DEFINITION
REJECTED = "REJECTED"
SPECIAL = "SPECIAL"
STANDARD = "STANDARD"
